@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()

Person(devActor, "Developer", "")
Person(managerActor, "Project Manager", "")
System(systemApp, "ProjectManager System", "Allows managers and developers to manage, view and keep track of projects.")
System_Ext(emailSystem, "E-mail system", "E-mail system not defined yet")

Rel(devActor, systemApp, "Uses")
Rel(managerActor, systemApp, "Uses")
Rel(emailSystem, devActor, "Sends e-mails to")
Rel(emailSystem, managerActor, "Sends e-mails to")
Rel(systemApp, emailSystem, "Sends e-mails", "SMTP")
@enduml

'//TODO Resaech and define e-mail system